### ISSUE TITLE
basic movement of code snippets

### ISSUE THREAD

**Issue by JuliaNocera** [team-jems/hrgame#2]
drag and drop? arrow keys? input field that responsively changes the appearance of the incorrect sample?

**Comment by JuliaNocera** [comment]
http://www.createjs.com/demos/easeljs/draganddrop

**Comment by ErikMHsiao** [comment]
Drag and drop would probably be something we aim for, but just clicking for selection and placement would work for MVP

**Comment by ErikMHsiao** [comment]
or this. https://jqueryui.com/draggable/#snap-to
