### ISSUE TITLE
timer countdown

### ISSUE THREAD

**Issue by mythsieh** [team-jems/hrgame#6]

**Comment by JuliaNocera** [comment]
?will each correct question add time back to the countdown or just keep things from getting worse? (jewels)

**Comment by mythsieh** [comment]
I imagined that each problem would be a stage, just like spaceteam

**Comment by mythsieh** [comment]
solving a problem before timer expires, next stage

**Comment by ErikMHsiao** [comment]
yeah, it'd be a bit sad if the user can never fix a reactor lol

**Comment by JuliaNocera** [comment]
cool :)
